name: Qase Test Upload
on:
  push:
    branches:
      - 'main'
    paths:
      - '**/schemas/**'
  
jobs:
  run-script:
    name: check-forks
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: "./go.mod"
          cache-dependency-path: "**/*.sum"

      - name: Check for Forked Branches
        env:
          QASE_AUTOMATION_TOKEN: ${{ secrets.QASE_AUTOMATION_TOKEN }}
        run: go run ./validation/pipeline/qase/schemaupload/main.go